
[general]
live_config_reload = true

[cursor]
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font.normal]
family = "Fira Code"

[scrolling]
history = 0

[selection]
save_to_clipboard = false

[terminal]

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = false
opacity = 0.8
startup_mode = "Maximized"

[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.cursor]
cursor = "0x657b83"
text = "0xfdf6e3"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0xfdf6e3"
foreground = "0x657b83"
