#!/bin/bash

set -e

if [ -d "$PWD/.venv/bin/activate" ]; then
	source "$PWD/.venv/bin/activate"
elif [ -d "$PWD/analytics/.venv/bin/activate" ]; then
	source "$PWD/analytics/.venv/bin/activate"
fi

nvim
